### ISSUE TITLE
Doesn't stop at breakpoint

### ISSUE THREAD

**Issue by mwilden** [astashov/vim-ruby-debugger#16]
This looks like a great tool! However, I haven't been able to make it stop at a breakpoint.

I start mvim with ' vim --servername VIM'
I go to the root of my Rails app in vim and enter ':Rdebugger'
I type \b and the breakpoint appears in the file
I run my app, but it doesn't stop. If I  put a 'raise' statement right above the breakpoint, that does get executed.
When I look back at the Terminal window, I see '2009-05-16 10:31:26.794 MacVim[86024:10b] [processInputQueues:] WARNING: No Vim controller for identifier=17'
When I look in "~/.vim/tmp/ruby_debugger_log" it is empty.

**Comment by astashov** [comment]
Hey, thanks for feedback!
But I need additional info from you. Could you please make sure you have 2 running processes after :Rdebugger command:
- rdebug-ide
- ruby ~/.vim/bin/ruby_debugger.rb

Also, check ~/.vim/tmp/ruby_debugger file after setting the breakpoint. It should have contents like this:
<breakpointAdded file="blabla" line="bla" />

~/.vim/tmp/ruby_debugger_log is cleared after starting vim. Check its contents immediatly after setting the breakpoint.
Thanks!

**Comment by astashov** [comment]
Also, what vim do you run? vim, mvim, gvim? Do other vim implementations not work too?

**Comment by mwilden** [comment]
ps -A includes

```
33845 ??         0:01.64 /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby /usr/bin/rdebug-ide -p 39767 -- script/server webrick
35547 ??         0:01.16 /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby /usr/bin/rdebug-ide -p 39767 -- script/server webrick
```

I see webrick in there. That doesn't look right. Anyway, I'm running Passenger.

I don't see a process for ruby_debugger.rb.

~/.vim/tmp/ruby_debugger has the timestamp of when I issued the :Rdebugger command, but it has 0 bytes.

**Comment by astashov** [comment]
1.  Two processes on one port is not okay. Looks like :Rdebugger doesn't kill them. Does MacOS have 'lsof' command? The plugin uses it for finding and killing servers.
2.  'script/server webrick' is default command of :Rdebugger. If you want to run something else, use :
   <pre><code>
   Rdebugger path/to/script
   </pre></code>
3. Okay, by some reason it can't run ruby_debugger.rb. Try to run it manually:
   <pre><code>
   ruby ~/.vim/bin/ruby_debugger.rb 39767 39768 mvim VIM /home/your_dir/.vim/tmp/ruby_debugger posix
   </code></pre>
   (change your_dir to your dir). Result should be... nothing. :) Just hanging on without any output (it runs listeners for 39767 and 39768 ports).

Thanks!

**Comment by mwilden** [comment]
OK, the main problem was that i didn't have a ~/.vim/bin folder before, so when I copied ruby_debugger.rb to it, it just created a file called bin. :) So :Rdebugger seems to be working fine. 

However, I don't quite understand how to use the debugger, I guess. I'm used to just throwing in a 'debugger' statement in my ruby code, and having the debugger start in the terminal window of the process - which is usually RSpec. I didn't understand that you have to actually start RSpec from within Vim? (Also, if Rdebugger takes a path as an argument, I think you should specify that in the Vim code so that completion works.)

**Comment by astashov** [comment]
No, you don't need 'debugger' statement. You just need to set some breakpoints before (or after) executing :Rdebugger by <Leader>b (current line should be highlighted by red color and there should be 'xx' symbols at left) and when execution reaches your breakpoint, Vim will jump to line with breakpoint. Like in the Netbeans. Then, you can watch variables, run :RdbCommand commands, etc.

I'm planning support of RSpec in the future (issue #13), so keep watching :), it will be added soon. It will be command like :RdbSpec, that will execute current spec (file where cursor is placed) and stop on breakpoints.

**Comment by astashov** [comment]
> if Rdebugger takes a path as an argument, I think you should specify 
> that in the Vim code so that completion works

Cool advice, thanks!

**Comment by mwilden** [comment]
Yes, I understand that you don't use the 'debugger' statement - I was just saying how I use rdebug. I thought/hoped/assumed that your vim debugger worked the same way.

Just so I understand, you need to start the program you're debugging from within Vim, right? Make sense - I just didn't realize that.

I'll look forward to the RSpec support!! Also, Cucumber would be good.

But should I be able to run an RSpec file 'manually' by specifying that command instead of the default that runs webrick?

**Comment by astashov** [comment]
> Just so I understand, you need to start the program you're debugging from within
> Vim, right? Make sense - I just didn't realize that.

Yup!

> I'll look forward to the RSpec support!! Also, Cucumber would be good.

I'll try to cover alll popular testing frameworks soon. (Rspec, Cucumber, Shoulda and standard Test::Unit). Actually, they are differ only by running command.

> But should I be able to run an RSpec file 'manually' by specifying that command
> instead of the default that runs webrick?

Should be something like

<pre>
<code>:Rdebugger '/usr/bin/spec /home/user/rails_app/spec/controllers/base_controller_spec.rb'</code>
</pre>

But now it doesn't work for me. I don't know why. I think I'll implement it this week.

**Comment by astashov** [comment]
Okay, support of Rspec, Cucumber and Test::Unit is added. I think I can close this issue...
