### ISSUE TITLE
ruby ~/.vim/bin/ruby_debugger.rb doesent start

### ISSUE THREAD

**Issue by antono** [astashov/vim-ruby-debugger#19]
I follow debug steps as was asked in issue 16 and found that 
ruby ~/.vim/bin/ruby_debugger.rb doesent started.

ruby /home/antono/.vim/bin/ruby_debugger.rb 39767 39768 vim VIM /home/antono/.vim/tmp/ruby_debugger posix
/home/antono/.vim/bin/ruby_debugger.rb:38:in `initialize': getaddrinfo: Servname not supported for ai_socktype (SocketError)
    from /home/antono/.vim/bin/ruby_debugger.rb:38:in`new'
    from /home/antono/.vim/bin/ruby_debugger.rb:38

cat /home/antono/.vim/tmp/ruby_debugger_{log,output} 
2009/05/22 04:16:02 Start debugger
2009/05/22 04:16:12 Set breakpoint to: /home/antono/Projects/blogo.old/app/controllers/articles_controller.rb:9

netstat -tapn | grep -E ":39767|:39768"
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 127.0.0.1:39767         0.0.0.0:\*               LISTEN      12831/ruby1.8

ps aux | grep debug
antono   12831  0.2  0.5  20240 10516 pts/2    Sl+  04:15   0:00 /usr/bin/ruby1.8 /var/lib/gems/1.8/bin/rdebug-ide -p 39767 -- script/server webrick
antono   13131  0.0  0.0   3336   808 pts/1    S+   04:20   0:00 grep --color=auto debug

**Comment by astashov** [comment]
Got it. Could you check values of ARGV[0] and ARGV[2] before 38 line in the ruby_debugger.rb file?

If they are equal to 'localhost' and 39768 accordingly, try to run 

```
    TCPSocket.new('localhost', 39768) 
```

in irb. What will it show?

**Comment by antono** [comment]
Just checked. 

ARGV[0] == 'ubook'
ARGV[2] == 39768

Just find that for some reason 
gethostip -d ubook
127.0.1.1
but 
gethostip -d localhost
127.0.0.1

Changed ip for `hostname` and all works now.

My fault.
Maybe you should force to localhost instead hostname? :)

**Comment by astashov** [comment]
Already did (see today's commits). Because vim's function hostname() gives _so strange_ results in WIndows ('E98BD9A419BB41D' instead of 'localhost')!

Okay, closing issue...
