### ISSUE TITLE
Doesn't debug Sinatra app on OS X

### ISSUE THREAD

**Issue by skammer** [astashov/vim-ruby-debugger#20]
I do precisely following:
1) Open my sinatra app in MacVim. :pwd shows the right directory
2) Run :Rdebugger sinatra_app.rb. Output says "Debugger started"
3) Set a breakpoint
4) Open up a browser, go to the page with a breakpoint and... the server is not running, so nothing happens. 

Clearly debugger does not even start the app.

**Comment by astashov** [comment]
Make sure you have two processes running after :Rdebugger command:
- rdebug-ide
- ruby ruby_debugger.rb

Please, show output of all files in ~/.vim/tmp directory.

**Comment by skammer** [comment]
When I run :Rdebugger first time it starts two processes, but after a few seconds one of them shuts down. I can't tell wich one of them is ruby_debugger, but the one that keeps running has multiple ports open (39768, 39767, 56590).

When I run :Rdebugger second time both processes keep running. The new one has only one port open (39767).

ruby_debugger file contains this string http://gist.github.com/118463
There are two more files – ruby_debugger_log and ruby_debugger_output – but they are empty.

**Comment by astashov** [comment]
Hmm... could you make sure what process exactly shuts down? It can help.
Meanwhile, I'll try to debug Sinatra on my local desktop.

**Comment by skammer** [comment]
The one with one open port.

**Comment by astashov** [comment]
Looks like it doesn't work for me too. :(
Please, try to set breakpoint to some first string (e.g., to require 'sinatra') before :Rdebugger command. And then, execute :Rdebugger. It should stop on this breakpoint. (as for me, the debugger behaves this way). 

But after this, if I press 'continue', it will not run the server. Strange... Maybe problem in the ruby-debug-ide gem. I'll try to debug manually, by this gem.

**Comment by astashov** [comment]
I've tried to debug it manually. I run:

<pre>
<code>[anton@localhost sinatra]$ rdebug-ide -p 39767 -- sinatra_app.rb
Fast Debugger (ruby-debug-ide 0.4.5) listens on localhost:39767</code></pre>


And in other console, run irb and execute:

<pre>
<code>[anton@localhost sinatra]$ irb
irb(main):001:0> require 'socket'
=> true
irb(main):002:0> a = TCPSocket.open('localhost', 39767)
=> #<TCPSocket:0xb7d2da68>
irb(main):003:0> a.puts('start')</code></pre>

After this, rdebug-ide just completed its work. Sinatra didn't run the server.

**Comment by skammer** [comment]
So at least we know the reason why it doesn't stop at breakpoints. It simply never runs.

**Comment by astashov** [comment]
Yeah... But if you want, you can set breakpoint to 'require 'sinatra'', run :Rdebugger, and try to understand why server doesn't start. Or just to make sure that debugger is working. :)

**Comment by astashov** [comment]
Seems to work now, with latest ruby-debug-ide and Sinatra 1.0.
