### ISSUE TITLE
locally set listchars for better reading

### ISSUE THREAD

**Issue by jfgomez86** [astashov/vim-ruby-debugger#22]
Some users (like me) don't like tabs or trailing spaces, so we use something like
set list listchars=tab:»·,trail:·
In order to see them (and then delete them with a nice :%s/\t/  /g | %s/\s+$//g ).
It would be super cool if you could set listchars to something non obstrusive regarding the variable window and any other window you use with the debugger (I've heard somewhere it can be done on a buffer basis) or just replace tabs with 2 spaces.

**Comment by astashov** [comment]
Yup, good point, will do.

**Comment by astashov** [comment]
Done.
