### ISSUE TITLE
can't detect rdebug-ide with lsof on Mac OS X

### ISSUE THREAD

**Issue by splhack** [astashov/vim-ruby-debugger#24]
Please take a look at the following patch
http://pastebin.com/m3caabf6f

```
-    let pid = system("lsof -i 4tcp@" . a:bind . ':' . a:port . " | grep LISTEN 
+    if has("macunix")
+      let lsof = "lsof -i tcp:" . a:port
+    else
+      let lsof = "lsof -i 4tcp@" . a:bind . ':' . a:port
+    endif
+    let pid = system(lsof . " | grep LISTEN | awk '{print $2}'")
```

**Comment by astashov** [comment]
Hmm, okay, I'll add this. Without this, lsof doesn't work on Mac OS X, right?

**Comment by splhack** [comment]
lsof can't find rdebug-ide because rdebug-ide (MacPorts ruby + ruby-debug-ide gem) uses IPv6. This patch works as well if rdebug-ide use IPv4.

ruby      5173 sakamoto    9u  IPv6  0x6e71a70      0t0  TCP *:39767 (LISTEN)

**Comment by astashov** [comment]
Well, then I can leave only 'let lsof = "lsof -i tcp:" . a:port' for mac and for *nix (without if/else), right? I mean:

<pre>
<code>let pid = system("lsof -i tcp:' . a:port . " | grep LISTEN | awk '{print $2}'")</code></pre>

**Comment by splhack** [comment]
I think so. It seems ok for every platform that has lsof.

**Comment by astashov** [comment]
Done. Thanks for patch!
