### ISSUE TITLE
Infinit Window blinking on windows.

### ISSUE THREAD

**Issue by bogdan** [astashov/vim-ruby-debugger#27]
After running :Rdebugger my gvim window starts blinking.
Text editing area doesn't respond to any command. But upper GUI menu works fine.

The command line says: Loading Debugger...

**Comment by astashov** [comment]
Hi!
Please send contents of log files (in vimfiles/tmp directory).

**Comment by bogdan** [comment]
I am not a skilled vim developer, but I tried to debug it and figure out that the script is doing something recursively then trying to execute:
  let self.debugger_pid = self._get_pid(self.debugger_port, 1)

**Comment by astashov** [comment]
Ah! It means ruby_debugger.rb is not started by some reason. Could you try to run it manually? For this, put after
           " Start in background
           if has("win32") || has("win64")
              silent exe '! start ' . rdebug
              let debugger = 'ruby "' . expand(self.runtime_dir . "/bin/ruby_debugger.rb") . '"' . debugger_parameters
this string:
         echo(debugger)
Then, please show this command (result of echo) and try to run it manually. And then, tell me what you've got. :)

**Comment by bogdan** [comment]
Seems I guess where the problem is: 
I put the ruby debugger files to: %VIM%\vimfiles but not to %USER%\vimfiles

That is why the plugin didn't locate debugger ruby script

**Comment by bogdan** [comment]
closing
