### ISSUE TITLE
current execution line is not highlighted

### ISSUE THREAD

**Issue by artk** [astashov/vim-ruby-debugger#28]
Hello!

I start vim with ' vim --servername VIM'
:cd <root_of_test_app>
:Rdebugger
Then I open test controller (:o app/controllers/test_controller.rb) and set breakpoint with \b. Breakpoint appears correctly.
When I run app it stops, if I type \c app runs again, so apparently breakpoint works. But I can't see current line mark.
Also variables window is empty, although there is one initialized before breakpoint 

what have I missed?

cat ruby_debugger_log
2009/11/17 23:11:59 Killed server with pid: 25730
2009/11/17 23:11:59 Killed server with pid: 25733
2009/11/17 23:11:59 Start debugger
2009/11/17 23:12:07 Set breakpoint to: /root/test/app/controllers/test_controller.rb:5
2009/11/17 23:12:19 Toggling window with name: variables
2009/11/17 23:12:19 Opened window with name: variables
2009/11/17 23:12:19 Start displaying data in window with name: variables
2009/11/17 23:12:19 Set focus to window with name: variables
2009/11/17 23:12:19 Inserted data to window with name: variables
2009/11/17 23:12:19 Restored view of window with name: variables
2009/11/17 23:12:19 Complete displaying data in window with name: variables
2009/11/17 23:12:19 Opened variables window
2009/11/17 23:12:29 Toggling window with name: variables
2009/11/17 23:12:29 Set focus to window with name: variables
2009/11/17 23:12:29 Closed window with name: variables
2009/11/17 23:12:29 Opened variables window
2009/11/17 23:12:30 Toggling window with name: frames
2009/11/17 23:12:30 Opened window with name: frames
2009/11/17 23:12:30 Start displaying data in window with name: frames
2009/11/17 23:12:30 Set focus to window with name: frames
2009/11/17 23:12:30 Inserted data to window with name: frames
2009/11/17 23:12:30 Restored view of window with name: frames
2009/11/17 23:12:30 Complete displaying data in window with name: frames
2009/11/17 23:12:30 Opened frames window
2009/11/17 23:12:32 Toggling window with name: frames
2009/11/17 23:12:32 Set focus to window with name: frames
2009/11/17 23:12:32 Closed window with name: frames
2009/11/17 23:12:32 Opened frames window
2009/11/17 23:12:33 Toggling window with name: breakpoints
2009/11/17 23:12:33 Opened window with name: breakpoints
2009/11/17 23:12:33 Start displaying data in window with name: breakpoints
2009/11/17 23:12:33 Set focus to window with name: breakpoints
2009/11/17 23:12:33 Inserted data to window with name: breakpoints
2009/11/17 23:12:33 Restored view of window with name: breakpoints
2009/11/17 23:12:33 Complete displaying data in window with name: breakpoints
2009/11/17 23:12:33 Opened breakpoints window
2009/11/17 23:13:11 Continue

cat ruby_debugger_output
Fast Debugger (ruby-debug-ide 0.4.9) listens on :39767
=> Booting WEBrick
=> Rails 2.3.4 application starting on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
[2009-11-17 23:12:01] INFO  WEBrick 1.3.1
[2009-11-17 23:12:01] INFO  ruby 1.8.7 (2009-06-12) [x86_64-linux]
[2009-11-17 23:12:01] INFO  WEBrick::HTTPServer#start: pid=28052 port=3000
  SQL (0.1ms)   SET NAMES 'utf8'
  SQL (0.1ms)   SET SQL_AUTO_IS_NULL=0

Processing TestController#index (for 127.0.0.1 at 2009-11-17 23:12:13) [GET]
Completed in 58319ms (View: 5, DB: 0) | 200 OK [http://localhost/test]

**Comment by artk** [comment]
It was my fault, sorry =)

**Comment by astashov** [comment]
Sorry, I've just noticed this issue. So, the issue is solved, isn't it?

**Comment by artk** [comment]
Yes, it is solved.
I'm not sure what was wrong and I feel too lazy to find it out now :-D. I've made haste to post the bug, sorry.
The plugin is great =) Thank you!

**Comment by solidline** [comment]
I had the same problem using macvim. The issue was vim-ruby-debugger was calling my vim in /usr/bin. I created a symbolic link in /usr/local/bin so when vim is called from the debugger it points to macvim.

**Comment by bigloser** [comment]
I'm seeing this issue too, it seems to work fine except for showing the current execution line.  I've tried to use solidline solution, but it doesn't seem to help.  Any ideas, as there doesn't seem to be anything in the logs etc that would give a hint as to why it is not showing.

**Comment by bigloser** [comment]
FYI starting vim with the full path (in my case /opt/local/bin/vim --servername VIM) did the trick
