### ISSUE TITLE
Error, then clear all beackpoints

### ISSUE THREAD

**Issue by le0pard** [astashov/vim-ruby-debugger#29]
I have this error, then I try to clear all breackpoints ("\d")

E121: Неопределенная переменная: message
E116: Параметры для функции 211 заданы неверно
строка    2:
E716: Key not present in Dictionary: debugger_id
E15: Недопустимое выражение: 'delete ' . self.debugger_id
строка    3:
E121: Неопределенная переменная: message
E116: Параметры для функции 211 заданы неверно

What I do wrong?

**Comment by astashov** [comment]
What OS do you use? Linux, Win, MacOSX? If some POSIX, could you please check 'ps -ef' output, is there ruby_debugger.rb process running?

**Comment by le0pard** [comment]
Use linux. 
$ ps -ef | grep ruby
leo      19055     1  1 12:07 pts/0    00:00:20 /usr/bin/ruby1.8 /usr/bin/rdebug-ide -p 39767 -- script/server webrick
leo      19058     1  0 12:07 pts/0    00:00:00 ruby /home/user/.vim/bin/ruby_debugger.rb localhost 39767 39768 vim /home/user/.vim/tmp/ruby_debugger posix

Now I try set breakpoint and try to delete all "\d" I see error:

Обнаружена ошибка при обработке function 220..288..299:
строка    2:
E716: Key not present in Dictionary: debugger_id
E15: Недопустимое выражение: 'delete ' . self.debugger_id
строка    3:
E121: Неопределенная переменная: message
E116: Параметры для функции 211 заданы неверно

**Comment by astashov** [comment]
Aha. If you delete breakpoing by toggling it (set cursor to the breakpoint and press \b) - will it be removed?
And could you please show me logs from ~/.vim/tmp dir?

**Comment by le0pard** [comment]
> > Aha. If you delete breakpoing by toggling it (set cursor to the breakpoint and press \b) - will it be removed?

Deleted, but have the same error:
Обнаружена ошибка при обработке function 219..288..299:
строка    2:
E716: Key not present in Dictionary: debugger_id
E15: Недопустимое выражение: 'delete ' . self.debugger_id
строка    3:
E121: Неопределенная переменная: message
E116: Параметры для функции 211 заданы неверно

$ tail -f .vim/tmp/ruby_debugger_log
2010/04/09 14:05:07 Set breakpoint to: /home/user/.../some_controller.rb:13
2010/04/09 14:06:27 Set breakpoint to: /home/user/.../some_controller.rb:13

I didnt see in log delete of breakpoint :)

**Comment by le0pard** [comment]
Error begin on this file
vim/plugin/ruby_debugger.vim

on line 1648

" Send deleting breakpoint message to debugger, if it is run
" (e.g.: 'delete 5')
function! s:Breakpoint._send_delete_to_debugger() dict
  if has_key(g:RubyDebugger, 'server') && g:RubyDebugger.server.is_running()
    let message = 'delete ' . self.debugger_id # ERROR here :)
    call g:RubyDebugger.queue.add(message)
  endif
endfunction

**Comment by btelles** [comment]
Has anyone solved this?

**Comment by astashov** [comment]
@btelles
Can you repeat that? If you can, could you please enable logging, repeat that bug, and then send logs to me?

Thanks!

**Comment by btelles** [comment]
Hi Astashov, sure,

Here is the whole process:
1. start server (note that 'script/rails server' does not seem to work)
   :Rdebugger 'rails server' 
2. add breakpoint in a controller (in the middle of an action on a regular variable assignment)
   
   &lt;Leader>b
3. delete the same breakpoint
   
   &lt;Leader>b
4. Observe the following error (directly from logs: gvim -V1myviminfo...if there's another way to log stuff, just let me know.):

Loading debugger...
Debugger started

"app/controllers/roles_controller.rb" 
"app/controllers/roles_controller.rb" 90L, 2346C
                                                Reading viminfo file "/home/bernie/.viminfo" marks
not found in 'runtimepath': "macros/rails.vim"
No matching autocommands
No matching autocommands
No matching autocommands
:!RUBYOPT= ruby -w -c app/controllers/roles_controller.rb  &> /tmp/vAGSo5V/17

Error detected while processing function 225..294..304:
line    2:
E716: Key not present in Dictionary: debugger_id
E15: Invalid expression: 'delete ' . self.debugger_id
line    3:
E121: Undefined variable: message
E116: Invalid arguments for function 216
Writing viminfo file "/home/bernie/.viminfo"

**Comment by astashov** [comment]
It is really strange that script/rails server doesn't work. Do you use Rails 3?

No, I mean other log files, in the .vim/tmp dir. Enter ':help ruby-debugger-issues', there are instructions.
You have to add the line to your .vimrc:
let g:ruby_debugger_debug_mode = 1
Then restart vim, then do all these actions you described above, and then send files from the .vim/tmp dir to me (ruby_debugger, ruby_debugger_log, ruby_debugger_output). You can find my email in the :help ruby-debugger-about

Thanks!

**Comment by btelles** [comment]
Hah! I finally got it to work!
After doing all that you described above and a little troubleshooting, here's what I found:

When using the command:

```
:Rdebugger 'rails server'
the server starts, but when toggling breakpoints,  the file "ruby_debugger" does not 
get written to. BUT, the breakpoint array DOES get added, so when the plugin tries to remove the breakpoint, it doesn't find it.
```

When using the command:

```
:Rdebugger 'script/rails server'
The server DOES NOT start. Here's the error that shows up in ruby_debugger_output
```

Fast Debugger (ruby-debug-ide 0.4.9) listens on :39767
    /home/bernie/.rvm/gems/ruby-1.9.2-p180@turnimanager/gems/ruby-debug-ide19-0.4.12/lib/ruby-debug-ide.rb:123:in `debug_load'
    /home/bernie/.rvm/gems/ruby-1.9.2-p180@turnimanager/gems/ruby-debug-ide19-0.4.12/lib/ruby-debug-ide.rb:123:in`debug_program'
    /home/bernie/.rvm/gems/ruby-1.9.2-p180@turnimanager/gems/ruby-debug-ide19-0.4.12/bin/rdebug-ide:87:in `<top (required)>'
    /home/bernie/.rvm/gems/ruby-1.9.2-p180@turnimanager/bin/rdebug-ide:19:in`load'
    /home/bernie/.rvm/gems/ruby-1.9.2-p180@turnimanager/bin/rdebug-ide:19:in `<main>'
Uncaught exception: no such file to load -- script/rails

Finally, when using the command

```
:Rdebugger './script/rails server'
The tool works as expected.
```

This is somewhat odd. I wonder if it's a linux thing where it won't take script/rails. And the fact that using 'rails server' does not write to the expected file is a little strange.

Anywho, hope this helps. If you still want the logs, just let me know.

**Comment by astashov** [comment]
That is strange, it should resolve script/rails to absolute path. What Linux do you use?

**Comment by btelles** [comment]
Ubuntu 10.10 (both 32 and 64 bit editions)

**Comment by astashov** [comment]
Solved the issue with self.debugger_id in #41
