### ISSUE TITLE
Support\detect Rails 3

### ISSUE THREAD

**Issue by petRUShka** [astashov/vim-ruby-debugger#30]
If I try 
<code>:Rdebugger rails server</code>
I get error E172 ( Only one file name allowed).

P.S. Непонятно как отлаживать rails 3 в таком разе :)

**Comment by astashov** [comment]
Hi!

Hmm, I didn't try Rails 3 yet. Will try today!

**Comment by astashov** [comment]
This command works well for me:
    :Rdebugger 'script/rails server'
Try it!

**Comment by petRUShka** [comment]
I'm sorry, it is ok :)
My fail...
