### ISSUE TITLE
Doesn't run in my MacVim, Test-Unit fails

### ISSUE THREAD

**Issue by josefschmitz** [astashov/vim-ruby-debugger#31]
Thanks for developing such a great tool,
if I only could use it..

Im using mvim on Mac OS X and followed precisely your installing instructions.
I have ruby-debug-ide, lsof and ruby-debugger in ~/.vim/bundles/vim-ruby-debugger
installed with the pathogen-mechanism.

If I start the ruby-debugger, it takes several minutes to be up and running and then no variables or anything is displayed. In the log I find no error messages.

Running the Test-Unit takes almost 20 minutes (and is still not terminated). The output is:

"~/.vim/tmp/ruby_debugger_test_file" 2L, 17C written
Sorry, but you can set Exceptional Breakpoints only with running debugger
Loading debugger...
Debugger started
Sorry, but you can set Exceptional Breakpoints only with running debugger
Loading debugger...
Killing server with pid 62810

Please HELP me!
Thank you very much in advance

**Comment by astashov** [comment]
Hi!

Could you please send archived .vim and .vimrc to me? It will help me to recreate your environment and find the issue.

Thanks!

**Comment by astashov** [comment]
Fixed working with pathogen. Your issue should be fixed now.
