### ISSUE TITLE
Move path to ruby binary to separate valuable

### ISSUE THREAD

**Issue by petRUShka** [astashov/vim-ruby-debugger#32]
For example I have 3 version of ruby: 1.8, 1.9.1, 1.9.3. 
It would be great to have ability to change ruby version (or set path to ruby) via option in ~/.vim.rc

**Comment by bronson** [comment]
Would rvm http://rvm.beginrescueend.com/ be a better way of handling your situation?

**Comment by astashov** [comment]
Yeah, rvm is a better way to do that. Because you need to use not only other ruby, but other gem too (ruby-debug-ide19). Rvm handles that situation easily. I've added instructions how to use the plugin with Ruby 1.9 and Raild 3 to doc file, please take a look.

**Comment by petRUShka** [comment]
thank you, I will try rvm
