### ISSUE TITLE
Incompatible with Rails RVM and/or Rails3?

### ISSUE THREAD

**Issue by BrenCam** [astashov/vim-ruby-debugger#35]
Does this plugin work with the Rails RVM plugin which allows switching between different local  Ruby  environments. Link:  http://rvm.beginrescueend.com/rvm/basics/

After getting it to work w/out RVM I installed Rails 1.9.2 under RVM and found that the debugger no longer worked -   again possible issue with the ruby-ide-debugger gem. (I did reinstall this gem into the RVM environment  but this did not seem to help).

Can anyone else check this and confirm this as a bug/problem?

**Comment by astashov** [comment]
Works for me. Check the default path of rdebug-ide:
    which rdebug-ide
it should be something like ~/.rvm/blablabla, but not /usr/bin/rdebug-ide.
If it is /usr/bin/rdebug-ide - it will use old rdebug-ide library (for 1.8.7)

**Comment by astashov** [comment]
I added instructions how to work with Ruby 1.9 and RVM into the doc file. Check
    :help ruby-debugger-ruby19
