### ISSUE TITLE
Loading debugger... in Fedora 13 with Gvim

### ISSUE THREAD

**Issue by ghost** [astashov/vim-ruby-debugger#36]
Hi,

I installed all required gems (ruby-debug-ide, ruby-debug), placed Vim files on right directories and after that I launched gvim and opened my Sinatra 1.0 server.rb file.
Then I started debugger using ':Rdebugger' and I got 'Loading debugger....' which is great but unfortunately this message stays here for a long time (about 2 minutes) and also my Vim looks 'blocked'. It possible to avoid this delay ? Maybe I missed some setting or some file.

**Comment by rosenfeld** [comment]
I'm having the same syntom in one of my computers. I'll try to investigate what is happening... I'm on Debian in both computers, so this is not related to Fedora.

**Comment by rosenfeld** [comment]
I've just got some time for investigating the problem and I found that change hostname to '127.0.0.1' has solved the problem for me. For some reason, 'localhost' is giving me "unreachable" error in Ruby. Please verify your /etc/hosts file. If 'localhost' happens to be associated to the ipv6 address too, it seems to cause problems to Ruby...

I think this bug could be closed and a comment about this could be added to the Troubleshooting section. Or maybe, you could change 'localhost' to '127.0.0.1' for avoiding this kind of problem...

**Comment by astashov** [comment]
Hmm, strange issue with localhost, I don't have anything like this on my machine... Okay, I'll add that to the ruby-debugger help.

**Comment by astashov** [comment]
I've replaced 'localhost' to '127.0.0.1'

**Comment by rosenfeld** [comment]
Thanks! :)
