### ISSUE TITLE
Directory with space bug

### ISSUE THREAD

**Issue by miker81** [astashov/vim-ruby-debugger#37]
Directory name with script "Test project" and file test.rb
:Rdebugger test.rb hangs  with "Loading debugger ..." because of string

let rdebug = 'rdebug-ide -p ' . self.rdebug_port . ' -- ' . script_name

produces broken output.

Ugly fix for this issue is to replace string with:

let rdebug = 'rdebug-ide -p ' . self.rdebug_port . ' -- ' . '''' . script_name . ''''

**Comment by astashov** [comment]
Right, good point, will fix.

**Comment by astashov** [comment]
Fixed.
