### ISSUE TITLE
Deleting a breakpoint using MASTER appears to raise

### ISSUE THREAD

**Issue by simmerz** [astashov/vim-ruby-debugger#41]
The xx disappears and I get this:

Error detected while processing function 152..223..234:
line 2:
E716: Key not present in Dictionary: debugger_id
E15: Invalid expression: 'delete ' . self.debugger_id
line 3:
E121: Undefined variable: message
E116: Invalid arguments for function 143

**Comment by btelles** [comment]
Hello, I'm getting exactly the same error with the latest release. Any idea whether this can be solved easily?

Error detected while processing function 225..294..304:
line    2:
E716: Key not present in Dictionary: debugger_id
E15: Invalid expression: 'delete ' . self.debugger_id
line    3:
E121: Undefined variable: message
E116: Invalid arguments for funct

**Comment by rweng** [comment]
+1

**Comment by freddy-dev** [comment]
Hi,

Even after applying the fix for issue #41. I still get this issue. Your help is much appreciated.

Error detected while processing function 13..82..92:
line    2:
E716: Key not present in Dictionary: debugger_id
E15: Invalid expression: 'delete ' . self.debugger_id
line    3:
E121: Undefined variable: message
E116: Invalid arguments for function 4

**Comment by astashov** [comment]
Need more info. :)
Could you please show your steps how you get that message beginning from Vim start?

Thanks!

**Comment by freddy-dev** [comment]
Thanks for your quick reply. 

I am using Rails 3.0.6 and Ruby 1.9.2 on RVM, ruby-debug-ide19, ruby-debug19, Mac snow leopard 10.0.6, VIM 7.3.
I have no problem when working on rails 2.x but I face this problem when I switch to rails 3.x.

The steps I followed,
1) Start up the VIM by issuing command = vim --servername VIM
2) I issued :Rdebugger 'rails server' ('script/rails server didn't work for me)
3) I check the the process = ps -ef | grep debug to see if the debugger has started
4) I checked the log ruby_debugger_output and verified that the server has successfully started
5) Then i make a breakpoint by \b and i see the line highlighted in red and marked xx
6) I start the browser and try to trigger the method where the breakpoint is set but debugger does not break at the specified line.
7) when I remove the breakpoint by pressing \b and I get the error.

I applied the fix that you specified but still the issue persist. 

Thanks

**Comment by astashov** [comment]
Couple of things: 
1. Could you please check, will the full path to scripts/rails work? (e.g. :Rdebugger '/Users/freddy/rails-project/script/rails s')
2. Please enable the debugging mode by adding 'let g:ruby_debugger_debug_mode = 1' to .vimrc and then send me logs from your ~/.vim/tmp (or ~/.vim/bundle/vim-ruby-debugger/tmp if you use pathogen).

Thanks!

**Comment by freddy-dev** [comment]
I checked with the full path and it still does not work. Debugging mode was already enabled in the .vimrc file.
I have kept the logs in public Gist https://gist.github.com/1054458#

Please let me know if you need more information. Thanks.

**Comment by freddy-dev** [comment]
Any progress astashov. 

Thanks!

**Comment by astashov** [comment]
Not yet, sorry, awfully busy now. :(
But I don't like the line 'Uncaught exception: superclass mismatch for class RemoteInterface' in your logs, looks like it is related by some way with it. Try to run rdebug-ide manually and check if you still get such error.

For that, open a Terminal window, and run

```
$ rdebug-ide -p 39767 -- /rubyonrails/projects/child_progress/script/rails
```

and then open another Terminal window and in irb run something like this:

```
require 'socket'
a = TCPSocket.open("localhost", 39767)
a.puts("start")
```

and then check in the first window, whether the exception 'superclass mismatch' will be raised there.
