### ISSUE TITLE
Make Friendly for Use with Pathogen

### ISSUE THREAD

**Issue by jherdman** [astashov/vim-ruby-debugger#42]
It'd be nice not to have to copy files out of the 'vim' directory to use this plugin with Pathogen.

**Comment by astashov** [comment]
Sorry, didn't get it. What do you mean by 'not to have to copy files out of the 'vim' directory'?

**Comment by jherdman** [comment]
I'm referring to the following step from the installation instructions:

<blockquote>Copy contents of 'vim' folder to your ~/.vim/ (or to ~/.vim/bundle/vim-ruby-debugger if you use pathogen). You should have 4 files there then: ~/.vim/autoload/ruby_debugger.vim, ~/.vim/plugin/ruby_debugger.vim, ~/.vim/bin/ruby_debugger.rb and ~/.vim/doc/ruby_debugger.txt First file is a debugger plugin loader, second is a debugger itself, third is a small ruby script, that makes interaction between the VIM and the ruby-debug-ide gem. Fourth is a documentation file.</blockquote>

**Comment by astashov** [comment]
Yes, you can copy these files to ~/.vim/bundle/vim-ruby-debugger instead of just ~/.vim, and use it with pathogen this way. Or you mean any additional support of pathogen?

**Comment by jherdman** [comment]
Additional support. I'd ideally like to not have to do this step if I'm using Pathogen. I think it's simply a matter of having the contents of the "vim" directory in the main directory of the plugin to begin with.

**Comment by astashov** [comment]
Sorry, didn't get it again. :) Is there any another way of using the plugin with pathogen (except copying the plugin's contents to ~/.vim/bundle/name-of-plugin)?

> I think it's simply a matter of having the contents of the "vim" directory in the main directory of the plugin to begin with

You mean in the main directory of the repo? If so, then sorry, but I can't do that. The 'vim' dir is actually the build dir. The 'ruby_debugger' dir contains files with classes, which can be build into the .vim file by collector.rb, which will place it into 'vim' dir. As for me, it is handy - people just need to copy contents of 'vim' dir to their ~/.vim or ~/.vim/bundle/vim-ruby-debugger.

Why don't you like that way? I really don't understand.

**Comment by bittersweet** [comment]
When you are used to installing other plugins by just having the plugin directory itself in the bundle directory it really becomes a hassle having to copy every file. 

The way pathogen is organized is having everything in the bundle directory which makes your .vim directory very clean, most of us really like that as it's easier and more organized and great for storing your configs in git.

**Comment by astashov** [comment]
I know, I use pathogen too, and all what you have to do for using vim-ruby-debugger with pathogen is to copy contents of http://github.com/astashov/vim-ruby-debugger/tree/master/vim to ~/.vim/bundle/vim-ruby-debugger. That's it. 2 commands:

```
$ git clone git://github.com/astashov/vim-ruby-debugger.git
$ cp -r ./vim-ruby-debugger/vim ~/.vim/bundle/vim-ruby-debugger
```

Easy, isn't it? So, I really don't understand what to improve there.

**Comment by rubiii** [comment]
i agree with everyone who thinks copying/linking the vim folder is wrong. i'm using quite a few plugins and never had to do this before.

**Comment by astashov** [comment]
Guys, I'm opened for any improvements, but I still don't understand what they are. :) Could you please show me the use case how would you want to install it by another way.

**Comment by astashov** [comment]
Okay, I've moved all plugin's dirs/files from the 'vim' dir to the root dir, and moved all 'development' files to the 'src' dir. This is what you wanted, right?
