### ISSUE TITLE
Improve logging performance

### ISSUE THREAD

**Issue by astashov** [astashov/vim-ruby-debugger#44]
Now to add one line to the log file, it reads whole the file into memory, adds one line and writes all that stuff back to the file. When the log file is large, it will affect performance very much. Need to find some way to write only to the end of the log file (preferably - the crossplatform way). If there is no chance to do it by VimL, then maybe Ruby?

**Comment by btelles** [comment]
Agreed, performance would probably be improved tremendously. Great idea!

**Comment by astashov** [comment]
Done! Thanks to @stephenprater and @agrussellknives :)
