### ISSUE TITLE
ruby 1.9.2 + rvm + rails 3.0.7 + pathogen + macvim

### ISSUE THREAD

**Issue by devth** [astashov/vim-ruby-debugger#48]
Hi,

I'm unable to get this to work - it never stops on my breakpoints. It's not clear from the README what server to even use. `:Rdebugger` doesn't start a server. Trying `:Rdebugger 'script/rails server'` or `:Rdebugger 'script/rails start'` just results in `E77: Too many file names`.

How can I use this?

Thanks

```
$ which rdebug-ide
/Users/trevorhartman/.rvm/gems/ruby-1.9.2-p180/bin/rdebug-ide

$ which ruby
/Users/trevorhartman/.rvm/rubies/ruby-1.9.2-p180/bin/ruby

Fast Debugger (ruby-debug-ide 0.4.9) listens on :39767
  /Users/trevorhartman/.rvm/gems/ruby-1.9.2-p180/gems/ruby-debug-ide19-0.4.12/lib/ruby-debug-ide.rb:123:in `debug_load'
  /Users/trevorhartman/.rvm/gems/ruby-1.9.2-p180/gems/ruby-debug-ide19-0.4.12/lib/ruby-debug-ide.rb:123:in `debug_program'
  /Users/trevorhartman/.rvm/gems/ruby-1.9.2-p180/gems/ruby-debug-ide19-0.4.12/bin/rdebug-ide:87:in `<top (required)>'
  /Users/trevorhartman/.rvm/gems/ruby-1.9.2-p180/bin/rdebug-ide:19:in `load'
  /Users/trevorhartman/.rvm/gems/ruby-1.9.2-p180/bin/rdebug-ide:19:in `<main>'
Uncaught exception: no such file to load -- script/server not found
```

**Comment by astashov** [comment]
Hmm, strange. It is sort of common problem there (E77: Too many file names), you are not alone, but I can't repeat that.
Try to use full path to the script/rails, i.e.:

```
:Rdebugger '/absolute/path/to/your/app/script/rails server'
```

**Comment by astashov** [comment]
Also, please try a fix, proposed by rweng, there:
https://github.com/rweng/vim-ruby-debugger/commit/5426b7db6f83e82a91363395a7dbbba8109edbe0

Thanks!

**Comment by astashov** [comment]
Included rweng's pull request, that should fix the problem.
