### ISSUE TITLE
Добавить переменную отвечающую за скрипт по-умолчанию вместо 'script/server webrick'

### ISSUE THREAD

**Issue by petRUShka** [astashov/vim-ruby-debugger#52]
https://github.com/astashov/vim-ruby-debugger/blob/master/autoload/ruby_debugger.vim#L437

```
let script_string = a:0 && !empty(a:1) ? a:1 : 'script/server webrick'
```

Было бы здорово сделать 'script/server webrick' какой-нибудь переменной, которую можно править в ~/.vimrc. Потому что, скажем, в моём случае 70% проектов -- Rails 3 и я бы поставил себе по-умолчанию 'script/rails s'.

**Comment by astashov** [comment]
Done -  g:ruby_debugger_default_script
E.g., you can add this to your .vimrc:

```
let g:ruby_debugger_default_script = "script/rails s"
```
