### ISSUE TITLE
Reload

### ISSUE THREAD

**Issue by Batou99** [astashov/vim-ruby-debugger#59]
After finding a bug when I make a change in the source code the debugger does not reload the context as if the changes did not happen. ¿Any way to reload the context automatically (I am in development mode) or do I have to stop and start the debugger again?

**Comment by astashov** [comment]
You mean a bug in your Rails application, right?
Debugger works just as usual running the Rails server by 'rails server' or 'script/rails' - i.e. it will reload classes which are in config.autoload_paths. To reload classes which are not there (i.e. in the lib dir by default), you will need to stop and start debugger, yes.

Actually, it is not about the debugger, it is about Rails behaviour itself.

**Comment by Batou99** [comment]
You're totally right (I feel really dumb)
I meant about reloading a /lib class (It looks like you have been
reading my app ;-)
Anyway I found a nice trick to reload /lib classes on the fly (see
here: http://hemju.com/2011/02/11/rails-3-quicktip-auto-reload-lib-folders-in-development-mode/)

Thank you for your quick response. (And for the nice plugin too)

I have another question: ¿Is there any way to open an irb shell while
debugging to access the context?

Thank you again

Batou

On Wed, Aug 31, 2011 at 5:51 PM, astashov
reply@reply.github.com
wrote:

**Comment by astashov** [comment]
When you stop on a breakpoint, you can run

```
:RdbEval your_command_here
```

and it will return the response of that command. E.g.:

```
:RdbEval User.find(id).name
```

or something like this. Have a look at ":help ruby-debugger", all that stuff is described there.

**Comment by Batou99** [comment]
Thank you astashov

I already knew that. I was thinking something more like :RdbEval irb
because if I have to evaluate lots of things (I usually do) it easier
to have a interactive terminal.
I will remap some F key to execute RdbEval to make it easier but I
thought that maybe there was a way to open a shell.

Anyway, thanks again for all the trouble and keep up the good work.
The plugin is awesome!

Best Regards

Batou

On Thu, Sep 1, 2011 at 3:41 AM, astashov
reply@reply.github.com
wrote:
