### ISSUE TITLE
Can this be used with ruby (not on rails)?

### ISSUE THREAD

**Issue by jagill** [astashov/vim-ruby-debugger#68]
I don't see anything obvious in the documentation, but maybe I'm just missing something?

To be clear, I'm using a pure ruby script, no rails, no server, nothing for the browser to point to.   But i'd love to debug it in vim!

**Comment by astashov** [comment]
This is in Vim doc, https://github.com/astashov/vim-ruby-debugger/blob/master/doc/ruby_debugger.txt#L141 :)
Just don't forget to put a breakpoint before running the script, of course, since it will start to execute immediatly after running.
