### ISSUE TITLE
'127.0.0.1:39768 can not be opened' in MacVim

### ISSUE THREAD

**Issue by anshumans** [astashov/vim-ruby-debugger#71]
I'm using MacVim and trying to debug using ruby-1.9.3-p0, and when I start Rdebugger on any .rb file, it says "Loading debugger ..." for a while before getting the following error:

127.0.0.1:39768 can not be opened
Error detected while processing function 6..2..<SNR>25_send_message_to_debugger
line 33:
SystemExit: (eval):17:in 'exit': exit

Any idea what the issue might be?

**Comment by astashov** [comment]
Nope, no idea. :(
Could you please:
1. Try to use 1.9.2
2. Make sure you have let g:ruby_debugger_debug_mode = 1 in your .vimrc, then reload MacVim and try again with :Rdebugger. Then, you will be able to find logs for debugger in ~/.vim/bundle/vim-ruby-debugger/tmp/ruby_debugger_logs. You can share them with me. :)

**Comment by anshumans** [comment]
Ok, I think I figured out the problem.  It didn't have to do with the plugin at all, it was an issue with currently with using ruby-debug-base19 and 1.9.3 (http://stackoverflow.com/questions/9155681/rails-3-2-0-rspec-debugger-not-working).  Downloading the right versions of linecache19 and ruby-debug-base19 has gotten me past this issue now.

Quick question before I close: is there a way to pass an include path to Rdebugger?  I need that to debug a specific .rb file.

**Comment by astashov** [comment]
Just do:

```
:Rdebugger 'path/to/your/file.rb'
```

You may avoid quotes if there are no whitespaces in the path.

**Comment by anshumans** [comment]
Sorry, I wasn't clear.  I meant, is there a way to pass an include path, similar to '-I' that's passed to ruby, to Rdebugger?

**Comment by astashov** [comment]
Oh, sorry. No, there is no way to do that for now. :(
As a workaround, you can add these dirs manually right in your Ruby file, into $LOAD_PATH. Not sure if it helps you...

**Comment by anshumans** [comment]
ok, thanks!
