### ISSUE TITLE
Не открывается страница в браузере

### ISSUE THREAD

**Issue by hinikato** [astashov/vim-ruby-debugger#72]
Пробую сделать как написано в README, успешно дохожу до шага 4, т.е. я сделал RDebugger, поставил брякпоинт и открылось окно:
Fast Debugger (ruby-debug-ide 0.4.17.beta9, ruby-debug-base 0.11.30.pre10) listens on 127.0.0.1:39767
=> Booting WEBrick
=> Rails 3.2.3 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server

Но браузер почему-то не открывает страницу localhost:3000, пишет:
Firefox can't establish a connection to the server at 127.0.0.1:3000.

В скрипте похоже используется старая версия rails, я прописал у себя в .vimrc:
let g:ruby_debugger_default_script = 'script/rails s'

Как решить эту проблему?

Еще кстати когда запускаешь RDebugger, открывается и закрывается много окон на панели задач, это не проблема, но выглядит странно...

Система Windows 7, вот вывод gem list:
abstract (1.0.0)
actionmailer (3.2.3)
actionpack (3.2.3)
active_utils (1.0.3)
activeadmin (0.4.4)
activemerchant (1.23.0, 1.22.0, 1.20.4)
activemodel (3.2.3)
activerecord (3.2.3)
activerecord-sqlserver-adapter (3.2.4)
activeresource (3.2.3)
activesupport (3.2.3)
acts_as_list (0.1.6, 0.1.4)
addressable (2.2.8)
akami (1.0.0)
ancestry (1.3.0)
archive-tar-minitar (0.5.2)
arel (3.0.2)
aws-sdk (1.5.2, 1.3.9)
bcrypt-ruby (3.0.1 x86-mingw32)
bourbon (2.1.0)
braintree (2.16.0)
builder (3.0.0)
bundler (1.1.3)
cancan (1.6.7)
capybara (1.1.2)
childprocess (0.3.2)
cocaine (0.2.1)
coffee-rails (3.2.2)
coffee-script (2.2.0)
coffee-script-source (1.3.3)
columnize (0.3.6)
database_cleaner (0.7.2, 0.7.1)
deface (0.8.0)
devise (2.1.0, 2.0.4)
devise-encryptable (0.1.1)
diff-lcs (1.1.3)
email_spec (1.2.1)
erubis (2.7.0)
execjs (1.4.0)
factory_girl (3.3.0, 2.6.4)
factory_girl_rails (3.3.0, 1.7.0)
faker (1.0.1)
fastercsv (1.5.5)
ffaker (1.14.0, 1.12.1)
ffi (1.0.11)
formtastic (2.2.0, 2.1.1)
guard (1.0.3)
guard-rspec (0.7.3, 0.5.11)
gyoku (0.4.4)
has_scope (0.5.1)
highline (1.6.12, 1.6.11)
hike (1.2.1)
httparty (0.8.3)
httpi (0.9.7)
i18n (0.6.0)
inherited_resources (1.3.1)
journey (1.0.3)
jquery-rails (2.0.2)
json (1.7.3)
kaminari (0.13.0)
launchy (2.1.0)
libwebsocket (0.1.3)
linecache19 (0.5.13)
mail (2.4.4)
meta_search (1.1.3)
mime-types (1.18)
money (5.0.0, 3.7.1)
multi_json (1.3.5)
multi_xml (0.5.1)
mysql2 (0.3.11 x86-mingw32)
nested_set (1.7.0)
nokogiri (1.5.2 x86-mingw32)
nori (1.1.0)
orm_adapter (0.0.7)
paperclip (3.0.4, 2.7.0)
pg (0.13.2 x86-mingw32)
polyamorous (0.5.0)
polyglot (0.3.3)
rabl (0.6.12, 0.6.5)
rack (1.4.1)
rack-cache (1.2)
rack-mount (0.8.3, 0.6.14)
rack-ssl (1.3.2)
rack-test (0.6.1)
rails (3.2.3)
railties (3.2.3)
rake (0.9.2.2)
ransack (0.6.0)
rbx-require-relative (0.0.9)
rd_awesome_nested_set (1.4.4)
rd_resource_controller (1.0.1)
rd_searchlogic (3.0.1)
rd_unobtrusive_date_picker (0.1.0)
rdoc (3.12)
responders (0.9.1)
rspec (2.10.0, 2.9.0)
rspec-core (2.10.1, 2.9.0)
rspec-expectations (2.10.0, 2.9.1)
rspec-mocks (2.10.1, 2.9.0)
rspec-rails (2.10.1, 2.9.0)
ruby-debug-base19x (0.11.30.pre10)
ruby-debug-ide (0.4.17.beta9)
ruby_core_source (0.1.5)
rubygems-update (1.8.24)
rubyzip (0.9.8)
sass (3.1.18)
sass-rails (3.2.5)
savon (0.9.9)
selenium-webdriver (2.21.2, 2.20.0)
shoulda-matchers (1.1.0, 1.0.0)
spree (1.1.1, 1.1.0)
spree_api (1.1.1, 1.1.0)
spree_auth (1.1.1, 1.1.0)
spree_cmd (1.1.1, 1.1.0)
spree_core (1.1.1, 1.1.0)
spree_dash (1.1.1, 1.1.0)
spree_promo (1.1.1, 1.1.0)
spree_sample (1.1.1, 1.1.0)
spree_skrill (1.0.2)
spree_usa_epay (1.0.2)
sprockets (2.4.3, 2.1.3)
sqlite3 (1.3.6 x86-mingw32)
state_machine (1.1.2)
stringex (1.4.0, 1.3.3)
thor (0.15.2, 0.14.6)
tilt (1.3.3)
treetop (1.4.10)
tzinfo (0.3.33)
uglifier (1.2.4)
uuidtools (2.1.2)
warden (1.2.0, 1.1.1)
wasabi (2.1.1)
will_paginate (3.0.3)
xpath (0.1.4)

Установливал Rails через RailsInstaller.

**Comment by astashov** [comment]
Я уже давно не тестировал на Windows, и у ее у меня даже нету чтобы проверить в чем дело. Боюсь, тут я ничем помочь не могу.

**Comment by hinikato** [comment]
Ясно.
