### ISSUE TITLE
Doesn't run on 1.9.3 rails 3.2+ and latest debug gems

### ISSUE THREAD

**Issue by fillman** [astashov/vim-ruby-debugger#75]
``` ruby
gem list
...
ruby-debug-base19x (0.11.30.pre10)
ruby-debug-ide (0.4.17.beta14)
...
```

In tmp/ruby_debug_output I see:
"Cannott load such file commands/server" error
.... then goes small trace

Sorry for not pasting the trace cuz I don't have it right now, but its really small and it's calling rdebug-ide on some line and gets this error.

P.S: Strange thing though I see when it start fast debugger it displays the following:
Fast Debugger (ruby-debug-ide 0.4.17.beta14, ruby-debug-base 0.11)

But when RubyMine start debugger it displays:
Fast Debugger (ruby-debug-ide 0.4.17.beta14, ruby-debug-base 0.11.30.pre10)

The difference as you may see is that RM uses my local gem and vim script not.

**Comment by fillman** [comment]
Found a fix! Stupid me, dont read help :)

``` vim
# run debiugger for rails 3+ as :Rdebugger 'script/rails server'
```

**Comment by astashov** [comment]
Yeah, and also:
https://github.com/astashov/vim-ruby-debugger/blob/master/doc/ruby_debugger.txt#L147
:)
