### ISSUE TITLE
Debugger

### ISSUE THREAD

**Issue by sencer** [astashov/vim-ruby-debugger#76]
Ruby debugger ide is not being maintained, so why not using this one?

https://github.com/cldwalker/debugger

**Comment by astashov** [comment]
vim-ruby-debugger actually requires ruby-debug-ide19, which allows to communicate with the debugger by sending and receiving XML. Not sure if debugger is compatible with ruby-debug-ide19.

**Comment by astashov** [comment]
Working hard right now to add 'ruby-debug-ide19' features into 'debugger'

https://github.com/cldwalker/debugger/pull/55
https://github.com/astashov/debugger/compare/improving-tests...xml-output

Stay tuned :)

**Comment by astashov** [comment]
Aaaand done! :) There is the [debugger-xml](http://github.com/astashov/debugger-xml), which works with the debugger gem, and replaces ruby-debug-ide19. Now, this gem is recommended for using with vim-ruby-debugger.
