### ISSUE TITLE
Rdebugger calls vim instead of mvim and fails --servername

### ISSUE THREAD

**Issue by aalavi** [astashov/vim-ruby-debugger#80]
Hello,

Thank you for creating this tool. I tried to give it a try but I found myself stuck after I followed the instruction in help. 

1- I run mvim and confirm "echo ruby_debugger-proname" returns 'mvim'
2- :Rdebugger my_ruby_file.rb and it returns "Loading debugger..." and stays there for weber
3- I check log/output files in tmp folder and here is the snapshot:
## ruby_debugger_log:

Vim plugin, 11:12:54: Executing :Rdebugger...
Vim plugin, 11:12:54: Initializing Server object
Vim plugin, 11:12:54: Stopping, pid is:
Vim plugin, 11:12:54: Starting Server, command: "'/Users/aalavi/projects/temp/conveyor-sim_delay-duration/lib/phantom/det_sim.rb' "
Vim plugin, 11:12:54: Executing command: rdebug-vim '/Users/aalavi/projects/temp/conveyor-sim_delay-duration/lib/phantom/det_sim.rb'  --file /Users/aalavi/.vim/tmp/ruby_debugger --output /Users/aalavi/.vim/tmp/ruby_debugger_output --socket /var/folders/xs/86kr0l396_582r03_m6m86h80000gp/T/vldYSLa/1 --logger_file /Users/aalavi/.vim/tmp/ruby_debugger_log --debug_mode 1 --vim_executable Vim --vim_servername VIM1 --separator ++vim-ruby-debugger-separator++
debugger-xml, 11:12:55 : Executing command: Vim --servername VIM1 -u NONE -U NONE --remote-send "<C-\\><C-N>:call RubyDebugger.establish_connection()<CR>"
Vim plugin, 11:12:55: PID: 1291
Vim plugin, 11:12:55: Waiting for starting debugger...
~                                                      
## ruby_debugger_output

VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Aug 16 2012 15:12:57)
Unknown option argument: "--servername"
More info with: "vim -h"

---

I run this on Mac, Ruby 2.0, MacVim 7.3. Somehow, the debugger still uses 'vim' instead of 'mvim', I guess.

Thank you for helping out,
Regards

**Comment by astashov** [comment]
Weird, it directly uses `g:ruby_debugger_progname`, are you sure there is no typo?
Could you please show me the piece of `.vimrc` with that setting?

Thanks!

**Comment by astashov** [comment]
Also, it probably won't work with Ruby 2.0, sorry. The 'debugger' gem, which this plugin uses as a debugger, doesn't support Ruby 2.0 good enough still.

**Comment by aalavi** [comment]
Thanks for looking into this...

$cat ~/.vimrc

set background=dark
colorscheme railscasts
syntax on
set guifont=Monaco:h15
set expandtab
set tabstop=4
set shiftwidth=2
set autoindent
set smartindent
set showmatch
set showcmd
let g:ruby_debugger_proname = 'mvim'
let g:ruby_debugger_debug_mode = 1

**Comment by astashov** [comment]
```
let g:ruby_debugger_proname = 'mvim'
```

Not proname, but progname :) You missed 'g'.

**Comment by aalavi** [comment]
Thank you... Debugger kicks in now... I yet to learn how to use it. Thank you very much and sorry for this mistake. I am new to whole linux/mac/ruby thing.
