### ISSUE TITLE
Debugger is not running

### ISSUE THREAD

**Issue by abonec** [astashov/vim-ruby-debugger#81]
Hello.
I installed debugger, debugger-xml and vim-ruby-debugger via Vundle.
After that I set in vimrc: 

```
let g:ruby_debugger_debug_mode = 1
let g:ruby_debugger_spec_path = 'rspec'
let g:ruby_debugger_default_script = 'rails s'
let g:ruby_debugger_no_maps = 1
```

And after restart gvim my action as:
1. Rdebugger (start server fine and it work on localhost:3000
2. set a breakpoint (in vim command line appear line "debugger is not running")

Server work fine but don't stop on breakpoints

Debugger log here: https://gist.github.com/abonec/1faf366754740b11e328

I use rvm on ubuntu.

**Comment by astashov** [comment]
Hmm, weird. Could you also please show the server's output, by `:RdbLog` command (or from ~/.vim/bundle/vim-ruby-debugger/tmp/ruby_debugger_output).

Thanks!

**Comment by abonec** [comment]
Its like normal server output with

```
=> Booting WEBrick
=> Rails 3.2.12 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
Unable to load thrift_native extension. Defaulting to pure Ruby libraries.
[2013-04-05 10:06:22] INFO  WEBrick 1.3.1
[2013-04-05 10:06:22] INFO  ruby 2.0.0 (2013-02-24) [i686-linux]
[2013-04-05 10:06:22] INFO  WEBrick::HTTPServer#start: pid=21530 port=3000
```

at start, and tons of requests from rails, nothing else.

**Comment by phanhaiquang** [comment]
@astashov ,

I got same problem. Server could start. 
When breakpoint is set, it shows "Debugger is not running"
The web browser could access the page as usual, but breakpoints do not work.

From GVIM, it shows below error after the message "Debugger is not running"
"E488: Trailing characters"

Thanks,

**Comment by astashov** [comment]
@phanhaiquang, it's hard to understand what's the problem without logs.
Check the ~/.vim/bundle/vim-ruby-debugger/tmp dir and send ruby_debugger\* files contents.

**Comment by phanhaiquang** [comment]
@astashov ,

Thank you much for prompt response.
I added log message as below

## ruby_debugger_output

=> Booting WEBrick
=> Rails 4.0.0 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2013-07-11 13:01:46] INFO  WEBrick 1.3.1
[2013-07-11 13:01:46] INFO  ruby 2.0.0 (2013-06-27) [x86_64-linux]
[2013-07-11 13:01:46] INFO  WEBrick::HTTPServer#start: pid=6095 port=3000

## ruby_debugger_log

Vim plugin, 13:01:44: Executing :Rdebugger...
Vim plugin, 13:01:44: Initializing Server object
Vim plugin, 13:01:44: Stopping, pid is: 
Vim plugin, 13:01:44: Starting Server, command: "'/home/quangphan/.rvm/gems/ruby-2.0.0-p247/bin/rails' s"
Vim plugin, 13:01:44: Executing command: rdebug-vim --file /home/quangphan/.vim/bundle/vim-ruby-debugger/tmp/ruby_debugger --output /home/quangphan/.vim/bundle/vim-ruby-debugger/tmp/ruby_debugger_output --socket /tmp/vy9Mk7n/3 --logger_file /home/quangphan/.vim/bundle/vim-ruby-debugger/tmp/ruby_debugger_log --debug_mode 1 --vim_executable gvim --vim_servername GVIM --separator ++vim-ruby-debugger-separator++ -- '/home/quangphan/.rvm/gems/ruby-2.0.0-p247/bin/rails' s
debugger-xml, 13:01:44 : Executing command: gvim --servername GVIM -u NONE -U NONE --remote-send "<C-\\><C-N>:call RubyDebugger.establish_connection()<CR>"
Vim plugin, 13:01:44: PID: 6095
Vim plugin, 13:01:44: Waiting for starting debugger...
Vim plugin, 13:01:44: Adding 'start' to queue
Vim plugin, 13:01:44: Executing queue
Vim plugin, 13:01:44: Sending a message to ruby_debugger.rb: 'start'
Vim plugin, 13:01:44: Debugger is successfully started
Vim plugin, 13:01:48: Trying to toggle a breakpoint in the file /home/quangphan/project/rails/ga/app/controllers/report_controller.rb:9
Vim plugin, 13:01:48: There is no already set breakpoint, so create new one
Vim plugin, 13:01:48: Set breakpoint to: /home/quangphan/project/rails/ga/app/controllers/report_controller.rb:9
Vim plugin, 13:01:48: Added Breakpoint object to RubyDebugger.breakpoints array
Vim plugin, 13:01:48: Server is running, so add command to Queue
Vim plugin, 13:01:48: Adding 'break /home/quangphan/project/rails/ga/app/controllers/report_controller.rb:9' to queue
Vim plugin, 13:01:48: Executing queue
Vim plugin, 13:01:48: Sending a message to ruby_debugger.rb: 'break /home/quangphan/project/rails/ga/app/controllers/report_controller.rb:9'2126 /home/quangphan/.vim/bundle/vim-ruby-debugger/tm

**Comment by liuxuan30** [comment]
have you check in vim, 

:echo servername and see GVIM?

**Comment by liuxuan30** [comment]
sorry, should be :echo v:servername

Also are you using VM or ssh? see https://github.com/astashov/vim-ruby-debugger/issues/85

watch out for ssh -X

**Comment by astashov** [comment]
Hmm, it seems like vim sent a message to rdebug-vim, but rdebug-vim didn't confirm message receiving.
Could you please check if 'rdebug-vim' is still running? What OS do you use, btw?

**Comment by phanhaiquang** [comment]
@liuxuan30 
When I type ':echo v:servername' from gvim, it shows "GVIM"

@liuxuan30 , @astashov 
I am using Ububuntu 12.04 LTS.
When i use 'which rdebug-vim', it shows:
/home/quangphan/.rvm/gems/ruby-2.0.0-p247/bin/rdebug-vim

Could you please check if 'rdebug-vim' is still running?
-> could you please teach me how to confirm it ?

Thanks,

**Comment by astashov** [comment]
Do in your terminal

``` bash
ps -ef | grep rdebug-vim
```

It should show `rdebug-vim` process running.

**Comment by phanhaiquang** [comment]
So, rdebug-vim is not running.
from 'rdebug-vim -h', it said that the script is called inside vim-ruby-debugger.

Should I config or enable anything ?

**Comment by astashov** [comment]
Just to confirm, after you run `:Rdebugger` in gvim, and then setting the breakpoint, you do `ps -ef | grep rdebug-vim`, and it doesn't show that process?

**Comment by phanhaiquang** [comment]
I open gvim, execute :Rdebugger, and ps -ef | grep rdebug-vim
There is no process.

I mean, even if I did not set 'breakpoint' yet, it is no rdebug-vim process.
At this step, i got below message in 'ruby_debugger_log'
Vim plugin, 11:23:21: Debugger is successfully started

When using 'ps -ef', i see that rail server is started
(browser could access to the page)

**Comment by astashov** [comment]
Hmm... Try to run this command from logs then. Maybe it fails somehow after run?

``` bash
rdebug-vim --file /home/quangphan/.vim/bundle/vim-ruby-debugger/tmp/ruby_debugger --output /home/quangphan/.vim/bundle/vim-ruby-debugger/tmp/ruby_debugger_output --socket /tmp/vy9Mk7n/3 --logger_file /home/quangphan/.vim/bundle/vim-ruby-debugger/tmp/ruby_debugger_log --debug_mode 1 --vim_executable gvim --vim_servername GVIM --separator ++vim-ruby-debugger-separator++ -- '/home/quangphan/.rvm/gems/ruby-2.0.0-p247/bin/rails' s
```

**Comment by phanhaiquang** [comment]
I execute your command & it seems that there is no socket found (/tmp/vy9Mk7n/3)
I execute again :Rdebugger & it is now use another socket file: "--socket /tmp/vFcWBG8/1"

I tried

cd /tmp/vFcWBG8

ls -lF
total 0
srwxrwxr-x 1 quangphan quangphan 0 Jul 12 13:20 1=

ls -l
total 0
srwxrwxr-x 1 quangphan quangphan 0 Jul 12 13:20 1

I do not understand why it is '1=' in case of 'ls -lF', but '1' in case of 'ls'
When i 'cat' the file, it said 
'cat: 1: No such device or address'

I am not sure if this information is useful or not...

**Comment by astashov** [comment]
Oh yeah, vim-ruby-debugger creates a socket, and passes it to rdebug-vim, so rdebug-vim could listen incoming commands from it. But when you run the command with correct socket file, was that successful? It didn't show any errors?

**Comment by phanhaiquang** [comment]
When I execute with correct socket file, I got below error

2108 /home/quangphan/.vim/bundle/vim-ruby-debugger/tmp> rdebug-vim --socket /tmp/vY2UA3l/7 --debug_mode 1 --vim_executable gvim --vim_servername GVIM --separator ++vim-ruby-debugger-separator++
19430/home/quangphan/.rvm/gems/ruby-2.0.0-p247/gems/debugger-xml-0.1.4/lib/debugger/xml/extensions/vim_server.rb:9:in `reopen': no implicit conversion of nil into String (TypeError)
        from /home/quangphan/.rvm/gems/ruby-2.0.0-p247/gems/debugger-xml-0.1.4/lib/debugger/xml/extensions/vim_server.rb:9:in`start_for_vim'
        from /home/quangphan/.rvm/gems/ruby-2.0.0-p247/gems/debugger-xml-0.1.4/bin/rdebug-vim:22:in `run'
        from /home/quangphan/.rvm/gems/ruby-2.0.0-p247/gems/debugger-xml-0.1.4/bin/rdebug-vim:88:in`<top (required)>'
        from /home/quangphan/.rvm/gems/ruby-2.0.0-p247/bin/rdebug-vim:23:in `load'
        from /home/quangphan/.rvm/gems/ruby-2.0.0-p247/bin/rdebug-vim:23:in`<main>'
        from /home/quangphan/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in `eval'
        from /home/quangphan/.rvm/gems/ruby-2.0.0-p247/bin/ruby_noexec_wrapper:14:in`<main>'

**Comment by astashov** [comment]
Oh, crap, Ruby 2.0! vim-ruby-debugger doesn't support Ruby 2.0, because `debugger` gem doesn't fully support Ruby 2.0 so far. Sorry, I noticed that only right now.

**Comment by phanhaiquang** [comment]
@astashov 

Thank you very much for your great support   :)
I read the README & think that it supports Ruby >= 1.9.. (including 2.0)

It seems my issue becomes clear. 
But you you plan to support Ruby 2.0 ?

Thanks,

**Comment by astashov** [comment]
Yeah, sorry, I had to notice that earlier, from you initial logs post. :)

`vim-ruby-debugger` uses `debugger` gem under the hood, so as only `debugger` gem starts to support it, `vim-ruby-debugger` will automagically start to support it as well.

I wrote README before Ruby 2.0 came out, need to fix that :)

**Comment by abonec** [comment]
I should notice that when I started this issue I used debugger manually in command line. Debugger supports ruby 2 with p0.

**Comment by astashov** [comment]
Unfortunately, not enough yet.

```
Breakpoint 1 at a.rb:3
[-2, 7] in /Users/anton/projects/debugger-demo/a.rb
   1  a = 1
   2  b = 2
=> 3  c = a + b
   4  puts c
(rdb:1) where
dyld: lazy symbol binding failed: Symbol not found: _rb_vm_get_sourceline
  Referenced from: /Users/anton/projects/debugger-demo/vendor/bundle/ruby/2.0.0/gems/debugger-1.6.1/lib/ruby_debug.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_vm_get_sourceline
  Referenced from: /Users/anton/projects/debugger-demo/vendor/bundle/ruby/2.0.0/gems/debugger-1.6.1/lib/ruby_debug.bundle
  Expected in: flat namespace

Trace/BPT trap: 5
```
