### ISSUE TITLE
RdbStop not working

### ISSUE THREAD

**Issue by dhruvasagar** [astashov/vim-ruby-debugger#82]
Hey Astashov!

Thanks for the plugin and a lot of good work, the new update works quite well although I have faced quite a few issues, some of which I have been able to iron out.

Most of the issues are 'RVM' related, I have now moved to rbenv and confirm that the plugin now works much more smoothly.

However there is this one nagging weird problem, like the title says, RdbStop doesn't work. For some reason that is beyond me, it is not able to terminate / kill the rdebug-vim session. This is also possibly the reason why after using your plugin once, hangs gvim while trying to quit it (terminal vim works fine though, which is what I am using most of the times). I suspect the stalling is also due to your plugin which tries to shut the server and is unable to do so, though I could be wrong about that.

If I enable the debug mode using `let g:ruby_debygger_debug_mode=1` what I see in the ~/.vim/bundle/ruby_debugger/tmp_ruby_debugger_log file is this :

```
Vim plugin, 17:35:59: Stopping, pid is:
```

And nothing beyond or after that, I tried waiting for quite sometime.

Have you faced a similar issue ? What might be the probably cause ? Let me know if I could help you further to fix this.

**Comment by astashov** [comment]
Interesting... Could you please try one thing? If you open ~/.vim/bundle/ruby_debugger/tmp/ruby_debugger_log, you will see `rdebug-vim` command with a lot of arguments? Can you try to run it in console and see what happens, i.e. - what output?

Thanks!

**Comment by dhruvasagar** [comment]
Will try that out tonight.

**Comment by dhruvasagar** [comment]
If I try to execute the command manually in the terminal, it just spawns a rdebug-vim session, but vim is unable to connect to that session and reports debugger is not running.

The debugger is able to connect to a rdebug-vim session only if it is spawned by itself.

**Comment by astashov** [comment]
Yeah, but what's the output of that rdebug-vim command? It should display its own PID, and then - daemonize. Does it behave such way?

**Comment by dhruvasagar** [comment]
This is the command I executed :

```
ruby /home/dhruvasagar/.rbenv/versions/1.9.3-p385/bin/rdebug-vim /home/dhruvasagar/code/bounty/script/rails server --file /home/dhruvasagar/dotfiles/vim/bundle/ruby_debugger/tmp/ruby_debugger --output /home/dhruvasagar/dotfiles/vim/bundle/ruby_debugger/tmp/ruby_debugger_output --socket /tmp/v6yqrUh/2 --logger_file /home/dhruvasagar/dotfiles/vim/bundle/ruby_debugger/tmp/ruby_debugger_log --debug_mode 0 --vim_executable vim --vim_servername BOUNTY --separator ++vim-ruby-debugger-separator++
```

The output is this : 

```
/home/dhruvasagar/dotfiles/rbenv/versions/1.9.3-p385/lib/ruby/gems/1.9.1/gems/debugger-1.5.0/lib/ruby-debug/printers/base.rb:7: warning: already initialized constant SEPARATOR
3295
```

Is it possible that the warning is causing issues ?

**Comment by dhruvasagar** [comment]
I think that is the issue. `let s:rdebug_pid = system(cmd)` is what you're using, since there is a warning, it is not the right pid :). Perhaps there should be some flag / option that ignores warnings ?

Should I update debugger or something ?

**Comment by astashov** [comment]
Could you please check, it should be fixed. BTW, the last version of 'debugger' should not produce these warnings too (https://github.com/cldwalker/debugger/issues/73)

**Comment by dhruvasagar** [comment]
Fixed, thanks!

**Comment by astashov** [comment]
Sweet. :)

**Comment by dhruvasagar** [comment]
I'd like to add, that now gvim also works without issues. Quitting doesn't stall it and it's able to stop the rdebug server.
