### ISSUE TITLE
Debuger not start

### ISSUE THREAD

**Issue by artofhuman** [astashov/vim-ruby-debugger#84]
I use rvm and after install ruby 2.0.0 debugger not start. 
In macvim i see Loading debugger....
In terminal i see error 

```
/Users/semen/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/x86_64-darwin12.2.1  /enc/encdb.bundle: warning: already initialized constant TMP_RUBY_PREFIX
```

hm
After uninstall ruby 2.0.0 and use alone 1.9.3
i see error

```
Vim: Caught deadly signal SEGV
vim-ruby: warning: already initialized constant TMP_RUBY_PREFIX
<internal:prelude>:2: warning: already initialized constant Thread::MUTEX_FOR_THREAD_EXCLUSIVE
<internal:prelude>:2: warning: previous definition of MUTEX_FOR_THREAD_EXCLUSIVE was here
```

**Comment by astashov** [comment]
Hey, AFAIK, 2.0.0 is not supported by the 'debugger' gem, and therefore by vim-ruby-debugger too.

**Comment by astashov** [comment]
And that's weird, there are no such constants in debugger or in vim-ruby-debugger...
