### ISSUE TITLE
Могу ли я использовать дебаггер, когда я запускаю задачи через tpope/vim-rake ?

### ISSUE THREAD

**Issue by dgorodnichybak** [astashov/vim-ruby-debugger#96]
У меня запуск кукумбер тестов реализван через запуск rake задач. Например:
`:Rake preprod features`
Есть ли возможность отлаживать код запущеный таким образом?

**Comment by astashov** [comment]
Нужно указывать путь до скрипта когда запускаешь дебаггер, например - ':Rdebugger /path/to/file.rb'. Если vim был запущен из той же директории где и скрипт, то можно делать ':Rdebugger rake blah'. Но дебаггер не интегрируется с vim-rake.
